// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsb8LsXHsVIXsJZtOBtd_b7KBi8R-Vjp0',
    appId: '1:660473066664:web:1c79ec456aa1cf03737e9d',
    messagingSenderId: '660473066664',
    projectId: 'authentication-dcecf',
    authDomain: 'authentication-dcecf.firebaseapp.com',
    storageBucket: 'authentication-dcecf.appspot.com',
    measurementId: 'G-FJ0HPKTMJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2G_FpMG8UNDR6Zm3Xj_xxfX5wz4LCxeI',
    appId: '1:660473066664:android:198463ec92285dd0737e9d',
    messagingSenderId: '660473066664',
    projectId: 'authentication-dcecf',
    storageBucket: 'authentication-dcecf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLuWGlELlbgoa_Rgg1UmF4EhKyMyM0RWc',
    appId: '1:660473066664:ios:b7dfd02ce133130d737e9d',
    messagingSenderId: '660473066664',
    projectId: 'authentication-dcecf',
    storageBucket: 'authentication-dcecf.appspot.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLuWGlELlbgoa_Rgg1UmF4EhKyMyM0RWc',
    appId: '1:660473066664:ios:b7dfd02ce133130d737e9d',
    messagingSenderId: '660473066664',
    projectId: 'authentication-dcecf',
    storageBucket: 'authentication-dcecf.appspot.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsb8LsXHsVIXsJZtOBtd_b7KBi8R-Vjp0',
    appId: '1:660473066664:web:311c254c2903a214737e9d',
    messagingSenderId: '660473066664',
    projectId: 'authentication-dcecf',
    authDomain: 'authentication-dcecf.firebaseapp.com',
    storageBucket: 'authentication-dcecf.appspot.com',
    measurementId: 'G-78QERFMHEH',
  );
}
